//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomaPedidos.OfertaVentaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessPartner", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceCliente.Dominio")]
    [System.SerializableAttribute()]
    public partial class BusinessPartner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPatField;
        
        private string CardCodeField;
        
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContctPrsnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicTradNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telephone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telephone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMat {
            get {
                return this.ApellidoMatField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMatField, value) != true)) {
                    this.ApellidoMatField = value;
                    this.RaisePropertyChanged("ApellidoMat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPat {
            get {
                return this.ApellidoPatField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPatField, value) != true)) {
                    this.ApellidoPatField = value;
                    this.RaisePropertyChanged("ApellidoPat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellular {
            get {
                return this.CellularField;
            }
            set {
                if ((object.ReferenceEquals(this.CellularField, value) != true)) {
                    this.CellularField = value;
                    this.RaisePropertyChanged("Cellular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContctPrsn {
            get {
                return this.ContctPrsnField;
            }
            set {
                if ((object.ReferenceEquals(this.ContctPrsnField, value) != true)) {
                    this.ContctPrsnField = value;
                    this.RaisePropertyChanged("ContctPrsn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicTradNum {
            get {
                return this.LicTradNumField;
            }
            set {
                if ((object.ReferenceEquals(this.LicTradNumField, value) != true)) {
                    this.LicTradNumField = value;
                    this.RaisePropertyChanged("LicTradNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone1 {
            get {
                return this.Telephone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telephone1Field, value) != true)) {
                    this.Telephone1Field = value;
                    this.RaisePropertyChanged("Telephone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone2 {
            get {
                return this.Telephone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telephone2Field, value) != true)) {
                    this.Telephone2Field = value;
                    this.RaisePropertyChanged("Telephone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDoc {
            get {
                return this.TipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocField, value) != true)) {
                    this.TipoDocField = value;
                    this.RaisePropertyChanged("TipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPer {
            get {
                return this.TipoPerField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPerField, value) != true)) {
                    this.TipoPerField = value;
                    this.RaisePropertyChanged("TipoPer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
    [System.SerializableAttribute()]
    public partial class EntityException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OfertaVentaWS.IOfertaVentaService")]
    public interface IOfertaVentaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/BusquedaClienteList", ReplyAction="http://tempuri.org/IOfertaVentaService/BusquedaClienteListResponse")]
        TomaPedidos.OfertaVentaWS.BusinessPartner[] BusquedaClienteList(string cardcode, string cardname, string docnum, string telephone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/BusquedaClienteList", ReplyAction="http://tempuri.org/IOfertaVentaService/BusquedaClienteListResponse")]
        System.Threading.Tasks.Task<TomaPedidos.OfertaVentaWS.BusinessPartner[]> BusquedaClienteListAsync(string cardcode, string cardname, string docnum, string telephone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/RegistrarCliente", ReplyAction="http://tempuri.org/IOfertaVentaService/RegistrarClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TomaPedidos.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/RegistrarClienteEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string RegistrarCliente(TomaPedidos.OfertaVentaWS.BusinessPartner businessPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/RegistrarCliente", ReplyAction="http://tempuri.org/IOfertaVentaService/RegistrarClienteResponse")]
        System.Threading.Tasks.Task<string> RegistrarClienteAsync(TomaPedidos.OfertaVentaWS.BusinessPartner businessPartner);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOfertaVentaServiceChannel : TomaPedidos.OfertaVentaWS.IOfertaVentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfertaVentaServiceClient : System.ServiceModel.ClientBase<TomaPedidos.OfertaVentaWS.IOfertaVentaService>, TomaPedidos.OfertaVentaWS.IOfertaVentaService {
        
        public OfertaVentaServiceClient() {
        }
        
        public OfertaVentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfertaVentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaVentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaVentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TomaPedidos.OfertaVentaWS.BusinessPartner[] BusquedaClienteList(string cardcode, string cardname, string docnum, string telephone) {
            return base.Channel.BusquedaClienteList(cardcode, cardname, docnum, telephone);
        }
        
        public System.Threading.Tasks.Task<TomaPedidos.OfertaVentaWS.BusinessPartner[]> BusquedaClienteListAsync(string cardcode, string cardname, string docnum, string telephone) {
            return base.Channel.BusquedaClienteListAsync(cardcode, cardname, docnum, telephone);
        }
        
        public string RegistrarCliente(TomaPedidos.OfertaVentaWS.BusinessPartner businessPartner) {
            return base.Channel.RegistrarCliente(businessPartner);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarClienteAsync(TomaPedidos.OfertaVentaWS.BusinessPartner businessPartner) {
            return base.Channel.RegistrarClienteAsync(businessPartner);
        }
    }
}
