//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOpportunityManagement.OfertaVentaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessPartner", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Dominio")]
    [System.SerializableAttribute()]
    public partial class BusinessPartner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPatField;
        
        private string CardCodeField;
        
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContctPrsnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicTradNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telephone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telephone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMat {
            get {
                return this.ApellidoMatField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMatField, value) != true)) {
                    this.ApellidoMatField = value;
                    this.RaisePropertyChanged("ApellidoMat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPat {
            get {
                return this.ApellidoPatField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPatField, value) != true)) {
                    this.ApellidoPatField = value;
                    this.RaisePropertyChanged("ApellidoPat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellular {
            get {
                return this.CellularField;
            }
            set {
                if ((object.ReferenceEquals(this.CellularField, value) != true)) {
                    this.CellularField = value;
                    this.RaisePropertyChanged("Cellular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContctPrsn {
            get {
                return this.ContctPrsnField;
            }
            set {
                if ((object.ReferenceEquals(this.ContctPrsnField, value) != true)) {
                    this.ContctPrsnField = value;
                    this.RaisePropertyChanged("ContctPrsn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicTradNum {
            get {
                return this.LicTradNumField;
            }
            set {
                if ((object.ReferenceEquals(this.LicTradNumField, value) != true)) {
                    this.LicTradNumField = value;
                    this.RaisePropertyChanged("LicTradNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone1 {
            get {
                return this.Telephone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telephone1Field, value) != true)) {
                    this.Telephone1Field = value;
                    this.RaisePropertyChanged("Telephone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone2 {
            get {
                return this.Telephone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telephone2Field, value) != true)) {
                    this.Telephone2Field = value;
                    this.RaisePropertyChanged("Telephone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDoc {
            get {
                return this.TipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocField, value) != true)) {
                    this.TipoDocField = value;
                    this.RaisePropertyChanged("TipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPer {
            get {
                return this.TipoPerField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPerField, value) != true)) {
                    this.TipoPerField = value;
                    this.RaisePropertyChanged("TipoPer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
    [System.SerializableAttribute()]
    public partial class EntityException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actividad", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Dominio")]
    [System.SerializableAttribute()]
    public partial class Actividad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cNivelPrioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cOportunidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cTipoActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cTipoRepeticionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dPersonaContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dRazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cCliente {
            get {
                return this.cClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.cClienteField, value) != true)) {
                    this.cClienteField = value;
                    this.RaisePropertyChanged("cCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cNivelPrioridad {
            get {
                return this.cNivelPrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.cNivelPrioridadField, value) != true)) {
                    this.cNivelPrioridadField = value;
                    this.RaisePropertyChanged("cNivelPrioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cOportunidad {
            get {
                return this.cOportunidadField;
            }
            set {
                if ((object.ReferenceEquals(this.cOportunidadField, value) != true)) {
                    this.cOportunidadField = value;
                    this.RaisePropertyChanged("cOportunidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cTipoActividad {
            get {
                return this.cTipoActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.cTipoActividadField, value) != true)) {
                    this.cTipoActividadField = value;
                    this.RaisePropertyChanged("cTipoActividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cTipoRepeticion {
            get {
                return this.cTipoRepeticionField;
            }
            set {
                if ((object.ReferenceEquals(this.cTipoRepeticionField, value) != true)) {
                    this.cTipoRepeticionField = value;
                    this.RaisePropertyChanged("cTipoRepeticion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cUsuario {
            get {
                return this.cUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.cUsuarioField, value) != true)) {
                    this.cUsuarioField = value;
                    this.RaisePropertyChanged("cUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dComentarios {
            get {
                return this.dComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.dComentariosField, value) != true)) {
                    this.dComentariosField = value;
                    this.RaisePropertyChanged("dComentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dPersonaContacto {
            get {
                return this.dPersonaContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.dPersonaContactoField, value) != true)) {
                    this.dPersonaContactoField = value;
                    this.RaisePropertyChanged("dPersonaContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dRazonSocial {
            get {
                return this.dRazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.dRazonSocialField, value) != true)) {
                    this.dRazonSocialField = value;
                    this.RaisePropertyChanged("dRazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fFin {
            get {
                return this.fFinField;
            }
            set {
                if ((this.fFinField.Equals(value) != true)) {
                    this.fFinField = value;
                    this.RaisePropertyChanged("fFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fInicio {
            get {
                return this.fInicioField;
            }
            set {
                if ((this.fInicioField.Equals(value) != true)) {
                    this.fInicioField = value;
                    this.RaisePropertyChanged("fInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fModificacion {
            get {
                return this.fModificacionField;
            }
            set {
                if ((this.fModificacionField.Equals(value) != true)) {
                    this.fModificacionField = value;
                    this.RaisePropertyChanged("fModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fRegistro {
            get {
                return this.fRegistroField;
            }
            set {
                if ((this.fRegistroField.Equals(value) != true)) {
                    this.fRegistroField = value;
                    this.RaisePropertyChanged("fRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nActividad {
            get {
                return this.nActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.nActividadField, value) != true)) {
                    this.nActividadField = value;
                    this.RaisePropertyChanged("nActividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTelefono {
            get {
                return this.nTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.nTelefonoField, value) != true)) {
                    this.nTelefonoField = value;
                    this.RaisePropertyChanged("nTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sEstado {
            get {
                return this.sEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.sEstadoField, value) != true)) {
                    this.sEstadoField = value;
                    this.RaisePropertyChanged("sEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oportunidad", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Dominio")]
    [System.SerializableAttribute()]
    public partial class Oportunidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnotacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroMotorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroPlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroSerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroVINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonaContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaVigenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anotaciones {
            get {
                return this.AnotacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.AnotacionesField, value) != true)) {
                    this.AnotacionesField = value;
                    this.RaisePropertyChanged("Anotaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCliente {
            get {
                return this.CodClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodClienteField, value) != true)) {
                    this.CodClienteField = value;
                    this.RaisePropertyChanged("CodCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCliente {
            get {
                return this.EmailClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailClienteField, value) != true)) {
                    this.EmailClienteField = value;
                    this.RaisePropertyChanged("EmailCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroMotor {
            get {
                return this.NroMotorField;
            }
            set {
                if ((object.ReferenceEquals(this.NroMotorField, value) != true)) {
                    this.NroMotorField = value;
                    this.RaisePropertyChanged("NroMotor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroPlaca {
            get {
                return this.NroPlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.NroPlacaField, value) != true)) {
                    this.NroPlacaField = value;
                    this.RaisePropertyChanged("NroPlaca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroSerie {
            get {
                return this.NroSerieField;
            }
            set {
                if ((object.ReferenceEquals(this.NroSerieField, value) != true)) {
                    this.NroSerieField = value;
                    this.RaisePropertyChanged("NroSerie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroVIN {
            get {
                return this.NroVINField;
            }
            set {
                if ((object.ReferenceEquals(this.NroVINField, value) != true)) {
                    this.NroVINField = value;
                    this.RaisePropertyChanged("NroVIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonaContact {
            get {
                return this.PersonaContactField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaContactField, value) != true)) {
                    this.PersonaContactField = value;
                    this.RaisePropertyChanged("PersonaContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlacaVigente {
            get {
                return this.PlacaVigenteField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaVigenteField, value) != true)) {
                    this.PlacaVigenteField = value;
                    this.RaisePropertyChanged("PlacaVigente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefCliente {
            get {
                return this.TelefClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefClienteField, value) != true)) {
                    this.TelefClienteField = value;
                    this.RaisePropertyChanged("TelefCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Email", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Dominio")]
    [System.SerializableAttribute()]
    public partial class Email : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base64ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTMLPartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageHrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageUUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReceiveConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextPartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base64Content {
            get {
                return this.Base64ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.Base64ContentField, value) != true)) {
                    this.Base64ContentField = value;
                    this.RaisePropertyChanged("Base64Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailFrom {
            get {
                return this.EmailFromField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailFromField, value) != true)) {
                    this.EmailFromField = value;
                    this.RaisePropertyChanged("EmailFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailTo {
            get {
                return this.EmailToField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailToField, value) != true)) {
                    this.EmailToField = value;
                    this.RaisePropertyChanged("EmailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTMLPart {
            get {
                return this.HTMLPartField;
            }
            set {
                if ((object.ReferenceEquals(this.HTMLPartField, value) != true)) {
                    this.HTMLPartField = value;
                    this.RaisePropertyChanged("HTMLPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageHref {
            get {
                return this.MessageHrefField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageHrefField, value) != true)) {
                    this.MessageHrefField = value;
                    this.RaisePropertyChanged("MessageHref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageUUID {
            get {
                return this.MessageUUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageUUIDField, value) != true)) {
                    this.MessageUUIDField = value;
                    this.RaisePropertyChanged("MessageUUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameFrom {
            get {
                return this.NameFromField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFromField, value) != true)) {
                    this.NameFromField = value;
                    this.RaisePropertyChanged("NameFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameTo {
            get {
                return this.NameToField;
            }
            set {
                if ((object.ReferenceEquals(this.NameToField, value) != true)) {
                    this.NameToField = value;
                    this.RaisePropertyChanged("NameTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReceiveConfirmation {
            get {
                return this.ReceiveConfirmationField;
            }
            set {
                if ((this.ReceiveConfirmationField.Equals(value) != true)) {
                    this.ReceiveConfirmationField = value;
                    this.RaisePropertyChanged("ReceiveConfirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextPart {
            get {
                return this.TextPartField;
            }
            set {
                if ((object.ReferenceEquals(this.TextPartField, value) != true)) {
                    this.TextPartField = value;
                    this.RaisePropertyChanged("TextPart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
    [System.SerializableAttribute()]
    public partial class NotificationException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Dominio")]
    [System.SerializableAttribute()]
    public partial class SMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SID {
            get {
                return this.SIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SIDField, value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OfertaVentaWS.IOfertaVentaService")]
    public interface IOfertaVentaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/BusquedaClienteList", ReplyAction="http://tempuri.org/IOfertaVentaService/BusquedaClienteListResponse")]
        SalesOpportunityManagement.OfertaVentaWS.BusinessPartner[] BusquedaClienteList(string cardcode, string cardname, string docnum, string telephone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/BusquedaClienteList", ReplyAction="http://tempuri.org/IOfertaVentaService/BusquedaClienteListResponse")]
        System.Threading.Tasks.Task<SalesOpportunityManagement.OfertaVentaWS.BusinessPartner[]> BusquedaClienteListAsync(string cardcode, string cardname, string docnum, string telephone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/RegistrarCliente", ReplyAction="http://tempuri.org/IOfertaVentaService/RegistrarClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/RegistrarClienteEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string RegistrarCliente(SalesOpportunityManagement.OfertaVentaWS.BusinessPartner businessPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/RegistrarCliente", ReplyAction="http://tempuri.org/IOfertaVentaService/RegistrarClienteResponse")]
        System.Threading.Tasks.Task<string> RegistrarClienteAsync(SalesOpportunityManagement.OfertaVentaWS.BusinessPartner businessPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/ActualizarCliente", ReplyAction="http://tempuri.org/IOfertaVentaService/ActualizarClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/ActualizarClienteEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string ActualizarCliente(SalesOpportunityManagement.OfertaVentaWS.BusinessPartner businessPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/ActualizarCliente", ReplyAction="http://tempuri.org/IOfertaVentaService/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<string> ActualizarClienteAsync(SalesOpportunityManagement.OfertaVentaWS.BusinessPartner businessPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EliminarCliente", ReplyAction="http://tempuri.org/IOfertaVentaService/EliminarClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/EliminarClienteEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string EliminarCliente(string CardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EliminarCliente", ReplyAction="http://tempuri.org/IOfertaVentaService/EliminarClienteResponse")]
        System.Threading.Tasks.Task<string> EliminarClienteAsync(string CardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/BusquedaActividadList", ReplyAction="http://tempuri.org/IOfertaVentaService/BusquedaActividadListResponse")]
        SalesOpportunityManagement.OfertaVentaWS.Actividad[] BusquedaActividadList(string nActividad, string codOport, string codCliente, string nombCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/BusquedaActividadList", ReplyAction="http://tempuri.org/IOfertaVentaService/BusquedaActividadListResponse")]
        System.Threading.Tasks.Task<SalesOpportunityManagement.OfertaVentaWS.Actividad[]> BusquedaActividadListAsync(string nActividad, string codOport, string codCliente, string nombCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/RegistrarActividad", ReplyAction="http://tempuri.org/IOfertaVentaService/RegistrarActividadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/RegistrarActividadEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string RegistrarActividad(SalesOpportunityManagement.OfertaVentaWS.Actividad actividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/RegistrarActividad", ReplyAction="http://tempuri.org/IOfertaVentaService/RegistrarActividadResponse")]
        System.Threading.Tasks.Task<string> RegistrarActividadAsync(SalesOpportunityManagement.OfertaVentaWS.Actividad actividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/ActualizarActividad", ReplyAction="http://tempuri.org/IOfertaVentaService/ActualizarActividadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/ActualizarActividadEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string ActualizarActividad(SalesOpportunityManagement.OfertaVentaWS.Actividad actividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/ActualizarActividad", ReplyAction="http://tempuri.org/IOfertaVentaService/ActualizarActividadResponse")]
        System.Threading.Tasks.Task<string> ActualizarActividadAsync(SalesOpportunityManagement.OfertaVentaWS.Actividad actividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EliminarActividad", ReplyAction="http://tempuri.org/IOfertaVentaService/EliminarActividadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/EliminarActividadEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string EliminarActividad(string nActividad, string cOportunidad, string cCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EliminarActividad", ReplyAction="http://tempuri.org/IOfertaVentaService/EliminarActividadResponse")]
        System.Threading.Tasks.Task<string> EliminarActividadAsync(string nActividad, string cOportunidad, string cCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/BusquedaOportunidadList", ReplyAction="http://tempuri.org/IOfertaVentaService/BusquedaOportunidadListResponse")]
        SalesOpportunityManagement.OfertaVentaWS.Oportunidad[] BusquedaOportunidadList(string codigo, string codcliente, string nombcliente, string personacontact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/BusquedaOportunidadList", ReplyAction="http://tempuri.org/IOfertaVentaService/BusquedaOportunidadListResponse")]
        System.Threading.Tasks.Task<SalesOpportunityManagement.OfertaVentaWS.Oportunidad[]> BusquedaOportunidadListAsync(string codigo, string codcliente, string nombcliente, string personacontact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/RegistrarOportunidad", ReplyAction="http://tempuri.org/IOfertaVentaService/RegistrarOportunidadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/RegistrarOportunidadEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string RegistrarOportunidad(SalesOpportunityManagement.OfertaVentaWS.Oportunidad oportunidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/RegistrarOportunidad", ReplyAction="http://tempuri.org/IOfertaVentaService/RegistrarOportunidadResponse")]
        System.Threading.Tasks.Task<string> RegistrarOportunidadAsync(SalesOpportunityManagement.OfertaVentaWS.Oportunidad oportunidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/ActualizarOportunidad", ReplyAction="http://tempuri.org/IOfertaVentaService/ActualizarOportunidadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/ActualizarOportunidadEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string ActualizarOportunidad(SalesOpportunityManagement.OfertaVentaWS.Oportunidad oportunidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/ActualizarOportunidad", ReplyAction="http://tempuri.org/IOfertaVentaService/ActualizarOportunidadResponse")]
        System.Threading.Tasks.Task<string> ActualizarOportunidadAsync(SalesOpportunityManagement.OfertaVentaWS.Oportunidad oportunidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EliminarOportunidad", ReplyAction="http://tempuri.org/IOfertaVentaService/EliminarOportunidadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.EntityException), Action="http://tempuri.org/IOfertaVentaService/EliminarOportunidadEntityExceptionFault", Name="EntityException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string EliminarOportunidad(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EliminarOportunidad", ReplyAction="http://tempuri.org/IOfertaVentaService/EliminarOportunidadResponse")]
        System.Threading.Tasks.Task<string> EliminarOportunidadAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EnviarCorreoElectronico", ReplyAction="http://tempuri.org/IOfertaVentaService/EnviarCorreoElectronicoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.NotificationException), Action="http://tempuri.org/IOfertaVentaService/EnviarCorreoElectronicoNotificationExcepti" +
            "onFault", Name="NotificationException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string EnviarCorreoElectronico(SalesOpportunityManagement.OfertaVentaWS.Email email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EnviarCorreoElectronico", ReplyAction="http://tempuri.org/IOfertaVentaService/EnviarCorreoElectronicoResponse")]
        System.Threading.Tasks.Task<string> EnviarCorreoElectronicoAsync(SalesOpportunityManagement.OfertaVentaWS.Email email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EnviarMensajeTexto", ReplyAction="http://tempuri.org/IOfertaVentaService/EnviarMensajeTextoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOpportunityManagement.OfertaVentaWS.NotificationException), Action="http://tempuri.org/IOfertaVentaService/EnviarMensajeTextoNotificationExceptionFau" +
            "lt", Name="NotificationException", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceOfertaVenta.Errores")]
        string EnviarMensajeTexto(SalesOpportunityManagement.OfertaVentaWS.SMS sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaVentaService/EnviarMensajeTexto", ReplyAction="http://tempuri.org/IOfertaVentaService/EnviarMensajeTextoResponse")]
        System.Threading.Tasks.Task<string> EnviarMensajeTextoAsync(SalesOpportunityManagement.OfertaVentaWS.SMS sms);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOfertaVentaServiceChannel : SalesOpportunityManagement.OfertaVentaWS.IOfertaVentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfertaVentaServiceClient : System.ServiceModel.ClientBase<SalesOpportunityManagement.OfertaVentaWS.IOfertaVentaService>, SalesOpportunityManagement.OfertaVentaWS.IOfertaVentaService {
        
        public OfertaVentaServiceClient() {
        }
        
        public OfertaVentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfertaVentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaVentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaVentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SalesOpportunityManagement.OfertaVentaWS.BusinessPartner[] BusquedaClienteList(string cardcode, string cardname, string docnum, string telephone) {
            return base.Channel.BusquedaClienteList(cardcode, cardname, docnum, telephone);
        }
        
        public System.Threading.Tasks.Task<SalesOpportunityManagement.OfertaVentaWS.BusinessPartner[]> BusquedaClienteListAsync(string cardcode, string cardname, string docnum, string telephone) {
            return base.Channel.BusquedaClienteListAsync(cardcode, cardname, docnum, telephone);
        }
        
        public string RegistrarCliente(SalesOpportunityManagement.OfertaVentaWS.BusinessPartner businessPartner) {
            return base.Channel.RegistrarCliente(businessPartner);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarClienteAsync(SalesOpportunityManagement.OfertaVentaWS.BusinessPartner businessPartner) {
            return base.Channel.RegistrarClienteAsync(businessPartner);
        }
        
        public string ActualizarCliente(SalesOpportunityManagement.OfertaVentaWS.BusinessPartner businessPartner) {
            return base.Channel.ActualizarCliente(businessPartner);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarClienteAsync(SalesOpportunityManagement.OfertaVentaWS.BusinessPartner businessPartner) {
            return base.Channel.ActualizarClienteAsync(businessPartner);
        }
        
        public string EliminarCliente(string CardCode) {
            return base.Channel.EliminarCliente(CardCode);
        }
        
        public System.Threading.Tasks.Task<string> EliminarClienteAsync(string CardCode) {
            return base.Channel.EliminarClienteAsync(CardCode);
        }
        
        public SalesOpportunityManagement.OfertaVentaWS.Actividad[] BusquedaActividadList(string nActividad, string codOport, string codCliente, string nombCliente) {
            return base.Channel.BusquedaActividadList(nActividad, codOport, codCliente, nombCliente);
        }
        
        public System.Threading.Tasks.Task<SalesOpportunityManagement.OfertaVentaWS.Actividad[]> BusquedaActividadListAsync(string nActividad, string codOport, string codCliente, string nombCliente) {
            return base.Channel.BusquedaActividadListAsync(nActividad, codOport, codCliente, nombCliente);
        }
        
        public string RegistrarActividad(SalesOpportunityManagement.OfertaVentaWS.Actividad actividad) {
            return base.Channel.RegistrarActividad(actividad);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarActividadAsync(SalesOpportunityManagement.OfertaVentaWS.Actividad actividad) {
            return base.Channel.RegistrarActividadAsync(actividad);
        }
        
        public string ActualizarActividad(SalesOpportunityManagement.OfertaVentaWS.Actividad actividad) {
            return base.Channel.ActualizarActividad(actividad);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarActividadAsync(SalesOpportunityManagement.OfertaVentaWS.Actividad actividad) {
            return base.Channel.ActualizarActividadAsync(actividad);
        }
        
        public string EliminarActividad(string nActividad, string cOportunidad, string cCliente) {
            return base.Channel.EliminarActividad(nActividad, cOportunidad, cCliente);
        }
        
        public System.Threading.Tasks.Task<string> EliminarActividadAsync(string nActividad, string cOportunidad, string cCliente) {
            return base.Channel.EliminarActividadAsync(nActividad, cOportunidad, cCliente);
        }
        
        public SalesOpportunityManagement.OfertaVentaWS.Oportunidad[] BusquedaOportunidadList(string codigo, string codcliente, string nombcliente, string personacontact) {
            return base.Channel.BusquedaOportunidadList(codigo, codcliente, nombcliente, personacontact);
        }
        
        public System.Threading.Tasks.Task<SalesOpportunityManagement.OfertaVentaWS.Oportunidad[]> BusquedaOportunidadListAsync(string codigo, string codcliente, string nombcliente, string personacontact) {
            return base.Channel.BusquedaOportunidadListAsync(codigo, codcliente, nombcliente, personacontact);
        }
        
        public string RegistrarOportunidad(SalesOpportunityManagement.OfertaVentaWS.Oportunidad oportunidad) {
            return base.Channel.RegistrarOportunidad(oportunidad);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarOportunidadAsync(SalesOpportunityManagement.OfertaVentaWS.Oportunidad oportunidad) {
            return base.Channel.RegistrarOportunidadAsync(oportunidad);
        }
        
        public string ActualizarOportunidad(SalesOpportunityManagement.OfertaVentaWS.Oportunidad oportunidad) {
            return base.Channel.ActualizarOportunidad(oportunidad);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarOportunidadAsync(SalesOpportunityManagement.OfertaVentaWS.Oportunidad oportunidad) {
            return base.Channel.ActualizarOportunidadAsync(oportunidad);
        }
        
        public string EliminarOportunidad(string codigo) {
            return base.Channel.EliminarOportunidad(codigo);
        }
        
        public System.Threading.Tasks.Task<string> EliminarOportunidadAsync(string codigo) {
            return base.Channel.EliminarOportunidadAsync(codigo);
        }
        
        public string EnviarCorreoElectronico(SalesOpportunityManagement.OfertaVentaWS.Email email) {
            return base.Channel.EnviarCorreoElectronico(email);
        }
        
        public System.Threading.Tasks.Task<string> EnviarCorreoElectronicoAsync(SalesOpportunityManagement.OfertaVentaWS.Email email) {
            return base.Channel.EnviarCorreoElectronicoAsync(email);
        }
        
        public string EnviarMensajeTexto(SalesOpportunityManagement.OfertaVentaWS.SMS sms) {
            return base.Channel.EnviarMensajeTexto(sms);
        }
        
        public System.Threading.Tasks.Task<string> EnviarMensajeTextoAsync(SalesOpportunityManagement.OfertaVentaWS.SMS sms) {
            return base.Channel.EnviarMensajeTextoAsync(sms);
        }
    }
}
